export default webf;
/**
 * Main entry point of js-core.
 *
 * Provides pure JavaScript utility functions such as string, array,
 * type checking, traversal, math and other helpers.
 *
 * @module webf
 */
declare const webf: {
    equals: (o1: any, o2: any, seen?: WeakMap<WeakKey, any>) => any;
    noop: () => void;
    sizeOf: (o: any) => number;
    flatten: (o: Object | any[]) => any[];
    strParseFloat: (val: any) => number;
    throttle: (func: any, wait: any, leading?: boolean, trailing?: boolean, context?: null) => (...args: any[]) => void;
    debounce: (func: Function, wait: number, immediate?: boolean, context?: Object) => Function;
    round: (val: any, precision?: number) => number;
    floorTo: (n: any, precision: any) => number;
    plancher: (n: any, precision: any) => number;
    min: (list: any, cmp_func: any) => number | undefined;
    max: (list: any, cmp_func: any) => number | undefined;
    dec2hex: (n: number) => string;
    hex2dec: (hex: string) => number;
    isWindow: (o: any) => boolean;
    isDocument: (o: any) => boolean;
    isDomElement: (o: any) => boolean;
    getStyle: (el: Element, cssRule: string) => string;
    randAlpha: (n: any) => string;
    randAlphaCs: (n: any) => string;
    randAlphaNum: (n: any) => string;
    randAlphaNumCs: (n: any) => string;
    randNum: (n: any) => string;
    rand: (range: any, n: any) => string;
    uniqid: (prefix?: string) => string;
    isString: (str: any) => boolean;
    isObject: (o: any) => boolean;
    isFunction: (f: any) => boolean;
    isPlainObject: (o: any) => boolean;
    isBoolean: (b: any) => boolean;
    isBool: (b: any) => boolean;
    isUndefined: (v: any) => boolean;
    isArrayLike: (o: any) => boolean;
    isArray: (a: any) => boolean;
    isDate: (o: any) => boolean;
    isEvent: (o: any) => boolean;
    isInteger: (n: any) => boolean;
    isInt: (n: any) => boolean;
    isFloat: (n: any) => boolean;
    isScalar: (v: any) => boolean;
    isEventSupported: (eventName: any) => boolean;
    isTouchDevice: () => boolean;
    each: <T>(o: Collection<T>, callback: (key: number | string, value: T, o: Collection<T>, index: number) => (void | boolean), context?: any) => typeof o;
    foreach: <T>(o: Collection<T>, callback: (value: T, key: number | string, o: Collection<T>, index: number) => (void | boolean), context?: any) => typeof o;
    map: <T, R>(o: Collection<T>, callback: (key: number | string, value: T, o: Collection<T>, index: number) => (R | null | false), context?: any) => Array<R>;
    reduce: <T, R>(o: Collection<T>, callback: (accumulator: R | T, value: T, key: any, index: number, o: Collection<T>) => R, initialValue?: R) => R;
    extend: <T>(...args: (boolean | T)[]) => T;
    clone: <T>(o: T) => T;
    merge: <T>(first: Collection<T>, second?: Collection<T>, ...args: Collection<T>[]) => Array<T>;
    inArray: (value: any, arr: Object | any[], index?: number, strict?: boolean) => boolean;
    indexOf: (arr: Array<any> | string, elt: any, from?: number) => number;
    lastIndexOf: (arr: Array<any> | string, elt: any, from?: number) => number;
    compareArray: (a1: any, a2: any) => any;
    arrayUnique: (arr: any) => any;
    array_unique: (arr: any) => any;
    arrayDiff: (array1: any, array2: any, strict?: boolean) => any;
    array_diff: (arr: any) => any;
    range: (size: any, startAt?: number, step?: number) => any[];
    trim: (str: any, char?: string) => any;
    ltrim: (str: any, char?: string) => any;
    rtrim: (str: any, char?: string) => any;
    stripMultipleSpaces: (str: any) => any;
    noAccent: (str: any) => any;
    br2nl: (str: any) => any;
    nl2br: (str: any) => any;
    ucfirst: (str: any) => any;
    lcfirst: (str: any) => any;
    insertTag: (str: any, tag: any, position?: number, length?: number) => string;
    substringIndex: (str: any, delimiter: any, index: any) => string;
    insert: (str: any, ins: any, n: any) => any;
    reverse: (str: any) => string;
    thousandSeparator: (value: any, separator?: string, pointDecimal?: string) => any;
    numberFormat: (number: any, decimals?: number, forceCentimes?: boolean, thousandSep?: string, pointDecimal?: string) => any;
    toPrice: (number: any, decimals?: number, forceCentimes?: boolean, thousandSep?: string, pointDecimal?: string) => any;
    pad: (str: string, pad_length: number, pad_str?: string, pad_type?: string) => string;
    rgb2hex: (r: number | number[], g?: number, b?: number) => string;
    rgbtohex: (r: number | number[], g?: number, b?: number) => string;
    hex2rgb: (hex: string) => number[];
    hextorgb: (hex: string) => number[];
    parse_url: (str: string) => Object;
    addUrlParam: (url: string, param: string | Object, value?: string | null) => string;
    decodeHtml: (str: any) => any;
    htmlquotes: (str: any) => any;
    htmlsimplequotes: (str: any) => any;
    repeat: (str: any, n: any) => string;
    stripTags: (str: any, tag: any) => any;
    toUrl: (str: any) => any;
    escapeRegex: (str: any) => any;
    camelCase: (str: any) => string;
    format: (str: any, ...args: any[]) => any;
    f: (str: any, ...args: any[]) => any;
    toCssClassName: (str: any) => any;
    hilite: (str: any, req: any, tag?: string) => any;
    formatSize: (bytes: any, decimalPoint?: string) => string;
    compareMixAlphaDigits: (a: any, b: any) => number;
};
import * as stringFunctions from './string.js';
import * as arrayFunctions from './array.js';
import * as traversal from './traversal.js';
import * as is from './is.js';
import * as random from './random.js';
import { getStyle } from './dom.js';
import dom from './dom.js';
import * as math from './math.js';
import * as utils from './utils.js';
import eventDispatcher from './eventDispatcher.js';
import Mouse from './Mouse.js';
import Translator from './Translator.js';
export { stringFunctions, arrayFunctions, traversal, is, random, getStyle, dom, math, utils, eventDispatcher, Mouse, Translator };
