export function trim(str: any, char?: string): any;
export function ltrim(str: any, char?: string): any;
export function rtrim(str: any, char?: string): any;
export function stripMultipleSpaces(str: any): any;
export function noAccent(str: any): any;
export function br2nl(str: any): any;
export function nl2br(str: any): any;
export function ucfirst(str: any): any;
export function lcfirst(str: any): any;
export function insertTag(str: any, tag: any, position?: number, length?: number): string;
export function substringIndex(str: any, delimiter: any, index: any): string;
export function insert(str: any, ins: any, n: any): any;
export function reverse(str: any): string;
export function thousandSeparator(value: any, separator?: string, pointDecimal?: string): any;
export function numberFormat(number: any, decimals?: number, forceCentimes?: boolean, thousandSep?: string, pointDecimal?: string): any;
export function toPrice(number: any, decimals?: number, forceCentimes?: boolean, thousandSep?: string, pointDecimal?: string): any;
export function pad(str: string, pad_length: number, pad_str?: string, pad_type?: string): string;
export function rgb2hex(r: number | number[], g?: number, b?: number): string;
export function rgbtohex(r: number | number[], g?: number, b?: number): string;
export function hex2rgb(hex: string): number[];
export function hextorgb(hex: string): number[];
export function parse_url(str: string): Object;
export function addUrlParam(url: string, param: string | Object, value?: string | null): string;
export function decodeHtml(str: any): any;
export function htmlquotes(str: any): any;
export function htmlsimplequotes(str: any): any;
export function repeat(str: any, n: any): string;
export function stripTags(str: any, tag: any): any;
export function toUrl(str: any): any;
export function escapeRegex(str: any): any;
export function camelCase(str: any): any;
export function format(str: any, ...args: any[]): any;
export function f(str: any, ...args: any[]): any;
export function toCssClassName(str: any): any;
export function hilite(str: any, req: any, tag?: string): any;
export function formatSize(bytes: any, decimalPoint?: string): string;
export function compareMixAlphaDigits(a: any, b: any): number;
